### ISSUE TITLE
Core dump v.1.2.1

### ISSUE THREAD

**Issue by stefonarch** [cronoh/nanovault#89]
As title, on up to date arch linux. 
```
$ bin/NanoVault-1.2.1-x86_64.AppImage 
installed: X-AppImage-BuildId=7f875db0-b536-11a9-37c0-2bb9a9bf9e9f image: X-AppImage-BuildId=7f875db0-b536-11a9-37c0-2bb9a9bf9e9f
Segmentation fault (core dumped)

```

edit: same for 1.2.0

**Comment by fu5ha** [comment]
Hmm... that shouldn't be possible to cause in user code with the tech nanovault is built on. Sounds like a bug in V8/Electron. Not sure what to tell you as far as debugging it, but just knowing there was a segfault isn't much to go on... :p

Perhaps try searching for segfaults with electron on arch and see if anyone's had similar issues with other Electron apps.

**Comment by stefonarch** [comment]
`
electron -v
v6.0.1
`
Other electron apps (4) are all  working fine. No issues on arch bug  trackers. 
Yeah, not much to debug...
Might try to compile it maybe to have it working.

**Comment by fu5ha** [comment]
You could try running it in a debugger and getting a stack trace if you're
comfortable with that sort of thing

**Comment by stefonarch** [comment]
just done ;)
```
Reading symbols from bin/NanoVault-1.2.1-x86_64.AppImage...
(No debugging symbols found in bin/NanoVault-1.2.1-x86_64.AppImage)
Starting program: /home/stef/bin/NanoVault-1.2.1-x86_64.AppImage 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[Detaching after fork from child process 31706]
process 31702 is executing new program: /usr/bin/bash
[Detaching after fork from child process 31711]
[Detaching after fork from child process 31712]
[Detaching after fork from child process 31713]
[Detaching after fork from child process 31714]
[Detaching after fork from child process 31715]
[Detaching after fork from child process 31716]
[Detaching after fork from child process 31720]
installed: X-AppImage-BuildId=6a0c3eb0-b261-11a9-304a-7f02c65d1e05 image: X-AppImage-BuildId=7f875db0-b536-11a9-37c0-2bb9a9bf9e9f
[Detaching after fork from child process 31724]

Gtk-WARNING (recursed) **: Impossibile trovare il motore del tema in module_path: «adwaita»,

Gtk-WARNING (recursed) **: Impossibile trovare il motore del tema in module_path: «adwaita»,

Gtk-WARNING (recursed) **: Impossibile trovare il motore del tema in module_path: «murrine»,

Gtk-WARNING (recursed) **: Impossibile trovare il motore del tema in module_path: «murrine»,

Gtk-WARNING (recursed) **: Impossibile trovare il motore del tema in module_path: «murrine»,

Gtk-WARNING (recursed) **: Impossibile trovare il motore del tema in module_path: «murrine»,

Gtk-WARNING (recursed) **: Impossibile trovare il motore del tema in module_path: «murrine»,

Gtk-WARNING (recursed) **: Impossibile trovare il motore del tema in module_path: «murrine»,

Gtk-WARNING (recursed) **: Impossibile trovare il motore del tema in module_path: «murrine»,

Gtk-WARNING (recursed) **: Impossibile trovare il motore del tema in module_path: «murrine»,

Gtk-WARNING (recursed) **: Impossibile trovare il motore del tema in module_path: «murrine»,

Gtk-WARNING (recursed) **: Impossibile trovare il motore del tema in module_path: «murrine»,

Gtk-WARNING (recursed) **: Impossibile trovare il motore del tema in module_path: «murrine»,
process 31702 is executing new program: /tmp/.mount_NanoVarPRLuO/app/nanovault
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff18c2700 (LWP 31734)]
[Detaching after fork from child process 31735]
[New Thread 0x7ffff079e700 (LWP 31736)]
[Detaching after fork from child process 31737]
[New Thread 0x7fffefd46700 (LWP 31738)]
[New Thread 0x7fffef545700 (LWP 31739)]
[New Thread 0x7fffeed44700 (LWP 31740)]
[New Thread 0x7fffee543700 (LWP 31741)]
[New Thread 0x7fffedd42700 (LWP 31742)]
[New Thread 0x7fffed541700 (LWP 31743)]
[Thread 0x7fffeed44700 (LWP 31740) exited]
[Detaching after fork from child process 31744]

Thread 1 "nanovault" received signal SIGSEGV, Segmentation fault.
0x000000000154b57e in hb_face_reference_table ()

```

**Comment by Eothred** [comment]
Can second this issue, have had it for some time now. Here's the back trace I got for what it's worth. I use Manjaro, which is Arch based, so maybe due to upgrade of some supporting libraries (electron doesn't sound like a bad suggestion of where the issue could be).

I tried removing ~/.config/NanoVault in case I had a configuration issue, did not help.

```
(gdb) run
Starting program: /home/yngvelevinsen/Applications/NanoVault-1.2.1-x86_64.AppImage 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[Detaching after fork from child process 11043]
process 11039 is executing new program: /usr/bin/bash
[Detaching after fork from child process 11047]
[Detaching after fork from child process 11048]
[Detaching after fork from child process 11049]
[Detaching after fork from child process 11050]
[Detaching after fork from child process 11051]
[Detaching after fork from child process 11052]
[Detaching after fork from child process 11056]
installed: X-AppImage-BuildId=7f875db0-b536-11a9-37c0-2bb9a9bf9e9f image: X-AppImage-BuildId=7f875db0-b536-11a9-37c0-2bb9a9bf9e9f
process 11039 is executing new program: /tmp/.mount_NanoVaVJY0o9/app/nanovault
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff10f0700 (LWP 11074)]
[Detaching after fork from child process 11075]
[New Thread 0x7fffeffad700 (LWP 11077)]
[Detaching after fork from child process 11078]
[New Thread 0x7fffef555700 (LWP 11079)]
[New Thread 0x7fffeed54700 (LWP 11080)]
[New Thread 0x7fffee553700 (LWP 11081)]
[New Thread 0x7fffedd52700 (LWP 11082)]
[New Thread 0x7fffed551700 (LWP 11083)]
[New Thread 0x7fffecd50700 (LWP 11084)]
[New Thread 0x7fffecd50700 (LWP 11085)]
[Thread 0x7fffecd50700 (LWP 11084) exited]
[Thread 0x7fffed551700 (LWP 11083) exited]
[New Thread 0x7fffed551700 (LWP 11086)]
[New Thread 0x7fffec54f700 (LWP 11087)]
[Thread 0x7fffeffad700 (LWP 11077) exited]
[Detaching after fork from child process 11088]

Thread 1 "nanovault" received signal SIGSEGV, Segmentation fault.
0x000000000154b57e in hb_face_reference_table ()
(gdb) bt
#0  0x000000000154b57e in hb_face_reference_table ()
#1  0x00007ffff3aea264 in  () at /usr/lib/libharfbuzz.so.0
#2  0x00007ffff3ae90dc in hb_ot_var_get_axis_infos () at /usr/lib/libharfbuzz.so.0
#3  0x00007ffff42ec66a in  () at /usr/lib/libpangoft2-1.0.so.0
#4  0x00007ffff5d2e923 in pango_font_get_hb_font () at /usr/lib/libpango-1.0.so.0
#5  0x00007ffff5d195e4 in  () at /usr/lib/libpango-1.0.so.0
#6  0x00007ffff5d19e5a in pango_shape_with_flags () at /usr/lib/libpango-1.0.so.0
#7  0x00007ffff5d233d6 in  () at /usr/lib/libpango-1.0.so.0
#8  0x00007ffff5d24310 in  () at /usr/lib/libpango-1.0.so.0
#9  0x00007ffff5d257fa in  () at /usr/lib/libpango-1.0.so.0
#10 0x00007ffff5d2868c in pango_layout_get_unknown_glyphs_count () at /usr/lib/libpango-1.0.so.0
#11 0x00007ffff63eb78c in  () at /usr/lib/libgtk-x11-2.0.so.0
#12 0x00007ffff63ee8a6 in  () at /usr/lib/libgtk-x11-2.0.so.0
#13 0x00007ffff5cc32c0 in g_type_create_instance () at /usr/lib/libgobject-2.0.so.0
#14 0x00007ffff5cdf63e in  () at /usr/lib/libgobject-2.0.so.0
#15 0x00007ffff5ce0a55 in g_object_new_with_properties () at /usr/lib/libgobject-2.0.so.0
#16 0x00007ffff5ce0b52 in g_object_new () at /usr/lib/libgobject-2.0.so.0
#17 0x0000000000911d43 in  ()
#18 0x0000000000911528 in  ()
#19 0x00000000009056d0 in  ()
#20 0x000000000090545b in  ()
#21 0x0000000003f5d1fb in brightray::BrowserMainParts::ToolkitInitialized() ()
#22 0x0000000000a8652c in  ()
#23 0x00000000009f7405 in  ()
#24 0x0000000000ae8b62 in  ()
#25 0x00000000010de578 in  ()
#26 0x00000000036ce02f in  ()
#27 0x00000000010de7e2 in  ()
#28 0x0000000003de5e08 in main ()
```

**Comment by Eothred** [comment]
Are we getting anywhere on this one? I might have some time over the weekend to try to investigate more.

Anyone had this issue and found a solution?

**Comment by Eothred** [comment]
So I managed to build a new version which seems to at least open for me and show my accounts etc. I have not tried to transact anything or do other testing.

What I did was, approximately
```bash
npm update
npm install @angular-devkit/core@0.0.29 --save
npm install
npm run wallet:build-desktop
npm run desktop:local
```

After that, I found the app in desktop-app/build/

I suspect then, that this bug is probably just to some crap with old versions of something. I also think #92 might be a duplicate of this issue.

**Comment by xxxserxxx** [comment]
This is still happening as of 1.2.1; FWICS, this has been open for 7 months.
